<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deportistas [
    <!ELEMENT deportistas (f1*, tenis*, futbol*)>
        <!ELEMENT f1 (#PCDATA)>
        <!ATTLIST f1 pais (ESP|ITA|ALE|FRA) "ESP">
        <!ELEMENT tenis (#PCDATA)>
        <!ATTLIST f1 tenis (ESP|ITA|ALE|FRA) "ESP">
        <!ELEMENT futbol (#PCDATA)>
        <!ATTLIST f1 futbol (ESP|ITA|ALE|FRA) "ESP">
]>
<deportistas>
    <f1 pais="ALE">Sebastian Vettel</f1>
    <f1>Fernando Alonso</f1>
    <f1 pais="ESP">Carlos Sainz</f1>
    <tenis>Rafael Nadal</tenis>
</deportistas>